#!/usr/bin/env bash
#
# The KVS differential fixture is generated by the TypeScript reference emulator and consumed
# by blockchain/contracts/test/KVSVerifier.t.sol. That test is the evidence behind KAURAX's
# strongest fault-proof claim: "404 differential cases against the TypeScript emulator".
#
# It compares the Solidity verifier against the *committed fixture*, not against the live
# emulator. So a change to the emulator does not fail it — the fixture simply goes stale and
# the test keeps passing against a frozen artefact while the two implementations diverge.
#
# Demonstrated, not assumed: changing VERYLOW from 3 to 4 in packages/kvs/src/gas.ts leaves
# all 29 emulator tests and all 6 verifier tests passing. Regenerate the fixture with that
# change in place and the verifier test fails immediately, as it should. The only thing
# missing was regenerating.
#
# This closes that loop: regenerate, and require the result to be what is committed.
#
#   ./tests/check-kvs-fixtures.sh
#
set -uo pipefail

_find_root() {
  local d; d="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  while [ "$d" != "/" ]; do
    [ -f "$d/pnpm-workspace.yaml" ] && { echo "$d"; return 0; }
    d="$(dirname "$d")"
  done
  echo "could not locate the repository root" >&2; return 1
}
ROOT="$(_find_root)" || exit 1
cd "$ROOT"

RED=$'\033[31m'; GREEN=$'\033[32m'; BOLD=$'\033[1m'; DIM=$'\033[2m'; RESET=$'\033[0m'
FIXTURES="blockchain/contracts/test/fixtures"

printf "\n${BOLD}Regenerating the KVS fixtures from the reference emulator${RESET}\n"

# The fixtures must already be committed and unmodified, or "unchanged after regeneration"
# would be measuring nothing.
if ! git diff --quiet -- "$FIXTURES" 2>/dev/null; then
  printf "  ${RED}FAIL${RESET}  %s already has uncommitted changes; commit or restore them first\n\n" "$FIXTURES"
  exit 1
fi

if ! OUT="$(pnpm --filter @kaurax/kvs fixtures 2>&1)"; then
  printf "  ${RED}FAIL${RESET}  the generator did not run\n"
  printf "${DIM}%s${RESET}\n\n" "$(printf '%s' "$OUT" | tail -15)"
  exit 1
fi
printf "${DIM}%s${RESET}\n" "$(printf '%s' "$OUT" | grep -E '^\[kvs\]' || true)"

if git diff --quiet -- "$FIXTURES"; then
  printf "  ${GREEN}OK${RESET}    the committed fixtures are exactly what the emulator produces\n"
  printf "\n${GREEN}${BOLD}The verifier is being checked against the current emulator.${RESET}\n\n"
  exit 0
fi

printf "  ${RED}FAIL${RESET}  regenerating changed the fixtures:\n"
git diff --stat -- "$FIXTURES" | sed 's/^/        /'
cat <<EOF

The emulator and the committed fixture disagree, which means KVSVerifier.t.sol has been
checking the Solidity verifier against a stale artefact. Both of these are wrong answers:

  - committing the regenerated fixture without reading the diff, and
  - reverting the fixture to make this pass.

Decide which implementation changed and whether that change was intended. If it was, commit
the regenerated fixture *and* confirm \`forge test --match-contract KVSVerifierTest\` still
passes — that is the check that says the two implementations still agree.
EOF
exit 1
