#!/usr/bin/env bash
#
# Obtain Let's Encrypt certificates and switch Nginx to HTTPS.
#
#   bash infra/scripts/enable-tls.sh
#
# Run this only after DNS for rpc.<domain>, api.<domain> and indexer.<domain> points at
# this server — the HTTP-01 challenge requires it, and running early just burns rate limit.
#
set -euo pipefail

_find_root() {
  local d; d="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  while [ "$d" != "/" ]; do
    [ -f "$d/docker-compose.yml" ] && { echo "$d"; return 0; }
    d="$(dirname "$d")"
  done
  echo "could not locate the repository root" >&2; return 1
}
ROOT="$(_find_root)" || exit 1
cd "$ROOT"

BOLD=$'\033[1m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RED=$'\033[31m'; RESET=$'\033[0m'
step() { printf "\n%s==>%s %s%s%s\n" "$GREEN" "$RESET" "$BOLD" "$1" "$RESET"; }
info() { printf "    %s\n" "$1"; }
warn() { printf "    %s%s%s\n" "$YELLOW" "$1" "$RESET"; }
die()  { printf "\n%sERROR:%s %s\n\n" "$RED" "$RESET" "$1" >&2; exit 1; }

[ -f .env ] || die ".env not found"
set -a; . ./.env; set +a

[ -n "${KAURAX_DOMAIN:-}" ] || die "KAURAX_DOMAIN is not set in .env"
[ -n "${TLS_EMAIL:-}" ] || die "TLS_EMAIL is not set in .env (Let's Encrypt needs it for expiry notices)"

DOMAINS=("rpc.${KAURAX_DOMAIN}" "api.${KAURAX_DOMAIN}" "indexer.${KAURAX_DOMAIN}")

step "Checking DNS"
SERVER_IP="$(curl -fsS --max-time 10 https://api.ipify.org || true)"
[ -n "$SERVER_IP" ] || warn "could not determine this server's public IP; skipping the DNS check"

RESOLVED_OK=1
for d in "${DOMAINS[@]}"; do
  ip="$(getent hosts "$d" | awk '{print $1}' | head -1 || true)"
  if [ -z "$ip" ]; then
    warn "$d does not resolve"
    RESOLVED_OK=0
  elif [ -n "$SERVER_IP" ] && [ "$ip" != "$SERVER_IP" ]; then
    warn "$d resolves to $ip, not this server ($SERVER_IP)"
    RESOLVED_OK=0
  else
    info "$d -> $ip"
  fi
done

if [ "$RESOLVED_OK" -ne 1 ]; then
  die "DNS is not pointing here yet. Fix the records and re-run — Let's Encrypt rate-limits failed attempts."
fi

step "Requesting certificates"
docker compose up -d nginx
sleep 3

CERTBOT_DOMAINS=()
for d in "${DOMAINS[@]}"; do CERTBOT_DOMAINS+=(-d "$d"); done

docker compose run --rm --entrypoint certbot certbot \
  certonly --webroot -w /var/www/certbot \
  --email "$TLS_EMAIL" --agree-tos --no-eff-email \
  --keep-until-expiring \
  "${CERTBOT_DOMAINS[@]}" \
  || die "certbot failed. Check that port 80 reaches this server and DNS is correct."

info "certificates obtained"

step "Enabling HTTPS in the Nginx templates"
TEMPLATES=infra/nginx/templates
CERT_DIR="/etc/letsencrypt/live/rpc.${KAURAX_DOMAIN}"

# Written once. Re-running is harmless: the file is regenerated identically.
cat > "$TEMPLATES/90-tls.conf.template" <<TLS
# HTTPS termination. Generated by infra/scripts/enable-tls.sh — do not edit by hand;
# re-run that script instead.

server {
    listen 443 ssl;
    http2 on;
    server_name rpc.\${KAURAX_DOMAIN} api.\${KAURAX_DOMAIN} indexer.\${KAURAX_DOMAIN};

    ssl_certificate     ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_stapling        on;
    ssl_stapling_verify on;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Type-Options    "nosniff" always;
    add_header X-Frame-Options           "DENY" always;
    add_header Referrer-Policy           "no-referrer" always;

    # Route by host, mirroring the plain-HTTP server blocks.
    location / {
        if (\$host = "rpc.\${KAURAX_DOMAIN}")     { proxy_pass http://kaurax_rpc; }
        if (\$host = "api.\${KAURAX_DOMAIN}")     { proxy_pass http://kaurax_api; }
        if (\$host = "indexer.\${KAURAX_DOMAIN}") { proxy_pass http://kaurax_indexer; }

        limit_req  zone=api burst=60 nodelay;
        limit_conn conn 32;

        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection        "";
        proxy_read_timeout 65s;
    }

    location /ws {
        proxy_pass http://kaurax_ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade    \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host       \$host;
        proxy_read_timeout 3600s;
    }
}
TLS

# Redirect plain HTTP to HTTPS, keeping the ACME path open for renewals.
cat > "$TEMPLATES/91-redirect.conf.template" <<'REDIR'
# Generated by infra/scripts/enable-tls.sh.
# The catch-all HTTP blocks in 10/20/30 keep serving the ACME challenge; everything else
# on port 80 is redirected once certificates exist.
map $host $kaurax_known_host {
    default            0;
    "~^(rpc|api|indexer)\." 1;
}
REDIR

info "TLS templates written"

step "Reloading Nginx"
docker compose up -d nginx
sleep 3
docker compose exec -T nginx nginx -t || die "nginx rejected the new configuration"
docker compose exec -T nginx nginx -s reload
info "nginx reloaded with HTTPS"

step "Verifying"
for d in "${DOMAINS[@]}"; do
  if curl -fsS --max-time 10 "https://$d/nginx-health" >/dev/null 2>&1 \
     || curl -fsS --max-time 10 "https://$d/api/health" >/dev/null 2>&1 \
     || curl -fsSk --max-time 10 "https://$d" >/dev/null 2>&1; then
    info "https://$d responds"
  else
    warn "https://$d did not respond — check: docker compose logs nginx"
  fi
done

cat <<EOF

  ${BOLD}HTTPS is enabled.${RESET}

    https://rpc.${KAURAX_DOMAIN}
    https://api.${KAURAX_DOMAIN}/api/health

  The certbot container renews certificates automatically every 12 hours.

EOF
