/**
 * ABI fragments for the KAURAX application contracts.
 *
 * Only the functions the frontends actually call. Kept here rather than duplicated per app
 * so a signature change breaks compilation in one place instead of drifting silently
 * across three apps.
 */

export const erc20Abi = [
  {type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{type: "string"}]},
  {type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{type: "string"}]},
  {type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{type: "uint8"}]},
  {type: "function", name: "totalSupply", stateMutability: "view", inputs: [], outputs: [{type: "uint256"}]},
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{name: "account", type: "address"}],
    outputs: [{type: "uint256"}],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [{name: "owner", type: "address"}, {name: "spender", type: "address"}],
    outputs: [{type: "uint256"}],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [{name: "spender", type: "address"}, {name: "amount", type: "uint256"}],
    outputs: [{type: "bool"}],
  },
  {
    type: "function",
    name: "transfer",
    stateMutability: "nonpayable",
    inputs: [{name: "to", type: "address"}, {name: "amount", type: "uint256"}],
    outputs: [{type: "bool"}],
  },
] as const;

export const kauraxNamesAbi = [
  {
    type: "function",
    name: "register",
    stateMutability: "payable",
    inputs: [{name: "label", type: "string"}, {name: "duration", type: "uint64"}],
    outputs: [{type: "bytes32"}],
  },
  {
    type: "function",
    name: "renew",
    stateMutability: "payable",
    inputs: [{name: "label", type: "string"}, {name: "duration", type: "uint64"}],
    outputs: [],
  },
  {
    type: "function",
    name: "setResolvedAddress",
    stateMutability: "nonpayable",
    inputs: [{name: "label", type: "string"}, {name: "resolved", type: "address"}],
    outputs: [],
  },
  {
    type: "function",
    name: "transferName",
    stateMutability: "nonpayable",
    inputs: [{name: "label", type: "string"}, {name: "newOwner", type: "address"}],
    outputs: [],
  },
  {
    type: "function",
    name: "setPrimaryName",
    stateMutability: "nonpayable",
    inputs: [{name: "label", type: "string"}],
    outputs: [],
  },
  {type: "function", name: "clearPrimaryName", stateMutability: "nonpayable", inputs: [], outputs: []},
  {
    type: "function",
    name: "resolve",
    stateMutability: "view",
    inputs: [{name: "label", type: "string"}],
    outputs: [{type: "address"}],
  },
  {
    type: "function",
    name: "primaryName",
    stateMutability: "view",
    inputs: [{name: "account", type: "address"}],
    outputs: [{type: "string"}],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{name: "label", type: "string"}],
    outputs: [{type: "address"}],
  },
  {
    type: "function",
    name: "recordOf",
    stateMutability: "view",
    inputs: [{name: "label", type: "string"}],
    outputs: [
      {name: "nameOwner", type: "address"},
      {name: "resolved", type: "address"},
      {name: "expiresAt", type: "uint64"},
      {name: "available", type: "bool"},
      {name: "inGrace", type: "bool"},
    ],
  },
  {
    type: "function",
    name: "isAvailable",
    stateMutability: "view",
    inputs: [{name: "label", type: "string"}],
    outputs: [{type: "bool"}],
  },
  {
    type: "function",
    name: "isValidLabel",
    stateMutability: "view",
    inputs: [{name: "label", type: "string"}],
    outputs: [{type: "bool"}],
  },
  {
    type: "function",
    name: "priceFor",
    stateMutability: "view",
    inputs: [{name: "label", type: "string"}, {name: "duration", type: "uint64"}],
    outputs: [{type: "uint256"}],
  },
  {type: "function", name: "GRACE_PERIOD", stateMutability: "view", inputs: [], outputs: [{type: "uint64"}]},
  {type: "function", name: "totalRegistrations", stateMutability: "view", inputs: [], outputs: [{type: "uint256"}]},
  {
    type: "event",
    name: "NameRegistered",
    inputs: [
      {name: "node", type: "bytes32", indexed: true},
      {name: "label", type: "string", indexed: false},
      {name: "owner", type: "address", indexed: true},
      {name: "expiresAt", type: "uint64", indexed: false},
      {name: "paid", type: "uint256", indexed: false},
    ],
  },
] as const;

export const swapRouterAbi = [
  {
    type: "function",
    name: "getAmountsOut",
    stateMutability: "view",
    inputs: [{name: "amountIn", type: "uint256"}, {name: "path", type: "address[]"}],
    outputs: [{type: "uint256[]"}],
  },
  {
    type: "function",
    name: "getAmountsIn",
    stateMutability: "view",
    inputs: [{name: "amountOut", type: "uint256"}, {name: "path", type: "address[]"}],
    outputs: [{type: "uint256[]"}],
  },
  {
    type: "function",
    name: "getReserves",
    stateMutability: "view",
    inputs: [{name: "tokenA", type: "address"}, {name: "tokenB", type: "address"}],
    outputs: [{name: "reserveA", type: "uint256"}, {name: "reserveB", type: "uint256"}],
  },
  {
    type: "function",
    name: "swapExactTokensForTokens",
    stateMutability: "nonpayable",
    inputs: [
      {name: "amountIn", type: "uint256"},
      {name: "amountOutMin", type: "uint256"},
      {name: "path", type: "address[]"},
      {name: "to", type: "address"},
      {name: "deadline", type: "uint256"},
    ],
    outputs: [{type: "uint256[]"}],
  },
  {
    type: "function",
    name: "swapExactKAXForTokens",
    stateMutability: "payable",
    inputs: [
      {name: "amountOutMin", type: "uint256"},
      {name: "path", type: "address[]"},
      {name: "to", type: "address"},
      {name: "deadline", type: "uint256"},
    ],
    outputs: [{type: "uint256[]"}],
  },
  {
    type: "function",
    name: "swapExactTokensForKAX",
    stateMutability: "nonpayable",
    inputs: [
      {name: "amountIn", type: "uint256"},
      {name: "amountOutMin", type: "uint256"},
      {name: "path", type: "address[]"},
      {name: "to", type: "address"},
      {name: "deadline", type: "uint256"},
    ],
    outputs: [{type: "uint256[]"}],
  },
  {
    type: "function",
    name: "addLiquidity",
    stateMutability: "nonpayable",
    inputs: [
      {name: "tokenA", type: "address"},
      {name: "tokenB", type: "address"},
      {name: "amountADesired", type: "uint256"},
      {name: "amountBDesired", type: "uint256"},
      {name: "amountAMin", type: "uint256"},
      {name: "amountBMin", type: "uint256"},
      {name: "to", type: "address"},
      {name: "deadline", type: "uint256"},
    ],
    outputs: [{type: "uint256"}, {type: "uint256"}, {type: "uint256"}],
  },
  {
    type: "function",
    name: "removeLiquidity",
    stateMutability: "nonpayable",
    inputs: [
      {name: "tokenA", type: "address"},
      {name: "tokenB", type: "address"},
      {name: "liquidity", type: "uint256"},
      {name: "amountAMin", type: "uint256"},
      {name: "amountBMin", type: "uint256"},
      {name: "to", type: "address"},
      {name: "deadline", type: "uint256"},
    ],
    outputs: [{type: "uint256"}, {type: "uint256"}],
  },
  {
    type: "function",
    name: "removeLiquidityKAX",
    stateMutability: "nonpayable",
    inputs: [
      {name: "token", type: "address"},
      {name: "liquidity", type: "uint256"},
      {name: "amountTokenMin", type: "uint256"},
      {name: "amountKAXMin", type: "uint256"},
      {name: "to", type: "address"},
      {name: "deadline", type: "uint256"},
    ],
    outputs: [{type: "uint256"}, {type: "uint256"}],
  },
  {
    type: "function",
    name: "quote",
    stateMutability: "pure",
    inputs: [
      {name: "amountA", type: "uint256"},
      {name: "reserveA", type: "uint256"},
      {name: "reserveB", type: "uint256"},
    ],
    outputs: [{type: "uint256"}],
  },
  {
    type: "function",
    name: "addLiquidityKAX",
    stateMutability: "payable",
    inputs: [
      {name: "token", type: "address"},
      {name: "amountTokenDesired", type: "uint256"},
      {name: "amountTokenMin", type: "uint256"},
      {name: "amountKAXMin", type: "uint256"},
      {name: "to", type: "address"},
      {name: "deadline", type: "uint256"},
    ],
    outputs: [{type: "uint256"}, {type: "uint256"}, {type: "uint256"}],
  },
] as const;

export const swapFactoryAbi = [
  {
    type: "function",
    name: "getPair",
    stateMutability: "view",
    inputs: [{name: "tokenA", type: "address"}, {name: "tokenB", type: "address"}],
    outputs: [{type: "address"}],
  },
  {type: "function", name: "allPairsLength", stateMutability: "view", inputs: [], outputs: [{type: "uint256"}]},
  {
    type: "function",
    name: "allPairs",
    stateMutability: "view",
    inputs: [{name: "index", type: "uint256"}],
    outputs: [{type: "address"}],
  },
] as const;

export const swapPairAbi = [
  {type: "function", name: "token0", stateMutability: "view", inputs: [], outputs: [{type: "address"}]},
  {type: "function", name: "token1", stateMutability: "view", inputs: [], outputs: [{type: "address"}]},
  {
    type: "function",
    name: "getReserves",
    stateMutability: "view",
    inputs: [],
    outputs: [{type: "uint112"}, {type: "uint112"}, {type: "uint32"}],
  },
  {type: "function", name: "totalSupply", stateMutability: "view", inputs: [], outputs: [{type: "uint256"}]},
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{name: "account", type: "address"}],
    outputs: [{type: "uint256"}],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [{name: "owner", type: "address"}, {name: "spender", type: "address"}],
    outputs: [{type: "uint256"}],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [{name: "spender", type: "address"}, {name: "amount", type: "uint256"}],
    outputs: [{type: "bool"}],
  },
] as const;

export const launchpadAbi = [
  {type: "function", name: "saleCount", stateMutability: "view", inputs: [], outputs: [{type: "uint256"}]},
  {
    type: "function",
    name: "getSale",
    stateMutability: "view",
    inputs: [{name: "saleId", type: "uint256"}],
    outputs: [
      {
        type: "tuple",
        components: [
          {name: "creator", type: "address"},
          {name: "token", type: "address"},
          {name: "tokensPerKax", type: "uint256"},
          {name: "tokensForSale", type: "uint256"},
          {name: "softCapWei", type: "uint256"},
          {name: "hardCapWei", type: "uint256"},
          {name: "minContributionWei", type: "uint256"},
          {name: "maxContributionWei", type: "uint256"},
          {name: "startsAt", type: "uint64"},
          {name: "endsAt", type: "uint64"},
          {name: "raisedWei", type: "uint256"},
          {name: "tokensSold", type: "uint256"},
          {name: "tokensDeposited", type: "bool"},
          {name: "finalised", type: "bool"},
          {name: "creatorPaid", type: "bool"},
          {name: "cancelled", type: "bool"},
          {name: "metadataURI", type: "string"},
        ],
      },
    ],
  },
  {
    type: "function",
    name: "statusOf",
    stateMutability: "view",
    inputs: [{name: "saleId", type: "uint256"}],
    outputs: [{type: "uint8"}],
  },
  {
    type: "function",
    name: "contributionOf",
    stateMutability: "view",
    inputs: [{name: "saleId", type: "uint256"}, {name: "buyer", type: "address"}],
    outputs: [{type: "uint256"}],
  },
  {
    type: "function",
    name: "allocationOf",
    stateMutability: "view",
    inputs: [{name: "saleId", type: "uint256"}, {name: "buyer", type: "address"}],
    outputs: [{type: "uint256"}],
  },
  {
    type: "function",
    name: "claimed",
    stateMutability: "view",
    inputs: [{name: "saleId", type: "uint256"}, {name: "buyer", type: "address"}],
    outputs: [{type: "bool"}],
  },
  {
    type: "function",
    name: "createSale",
    stateMutability: "nonpayable",
    inputs: [
      {name: "token", type: "address"},
      {name: "tokensPerKax", type: "uint256"},
      {name: "tokensForSale", type: "uint256"},
      {name: "softCapWei", type: "uint256"},
      {name: "hardCapWei", type: "uint256"},
      {name: "minContributionWei", type: "uint256"},
      {name: "maxContributionWei", type: "uint256"},
      {name: "startsAt", type: "uint64"},
      {name: "endsAt", type: "uint64"},
      {name: "metadataURI", type: "string"},
    ],
    outputs: [{type: "uint256"}],
  },
  {
    type: "function",
    name: "depositTokens",
    stateMutability: "nonpayable",
    inputs: [{name: "saleId", type: "uint256"}],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelSale",
    stateMutability: "nonpayable",
    inputs: [{name: "saleId", type: "uint256"}],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawRaise",
    stateMutability: "nonpayable",
    inputs: [{name: "saleId", type: "uint256"}],
    outputs: [],
  },
  {
    type: "function",
    name: "remainingCapacityWei",
    stateMutability: "view",
    inputs: [{name: "saleId", type: "uint256"}],
    outputs: [{type: "uint256"}],
  },
  {
    type: "function",
    name: "contribute",
    stateMutability: "payable",
    inputs: [{name: "saleId", type: "uint256"}],
    outputs: [],
  },
  {
    type: "function",
    name: "claimTokens",
    stateMutability: "nonpayable",
    inputs: [{name: "saleId", type: "uint256"}],
    outputs: [],
  },
  {
    type: "function",
    name: "refund",
    stateMutability: "nonpayable",
    inputs: [{name: "saleId", type: "uint256"}],
    outputs: [],
  },
  {
    type: "function",
    name: "finalise",
    stateMutability: "nonpayable",
    inputs: [{name: "saleId", type: "uint256"}],
    outputs: [],
  },
] as const;

/** Sale status, matching KauraxLaunchpad.Status. */
export const SALE_STATUS = [
  "Pending",
  "Funded",
  "Live",
  "Succeeded",
  "Failed",
  "Cancelled",
] as const;

export type SaleStatus = (typeof SALE_STATUS)[number];
