// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {KauraxFaultDisputeGame} from "../src/dispute/KauraxFaultDisputeGame.sol";
import {KauraxOneStepVerifier} from "../src/kvs/KauraxOneStepVerifier.sol";
import {KVSTypes} from "../src/kvs/KVSTypes.sol";

/// @notice End-to-end tests for the fault dispute game, played against a real KVS trace.
///
/// @dev The scenario is generated by `pnpm --filter @kaurax/kvs game-fixture`: a program
///      that adds two numbers, writes the result to storage and reads it back, together
///      with its honest trace and a proof for every step.
///
///      Every "the proposer lied" test tampers with exactly one field of the final state —
///      storage root, gas, stack root, program counter — rather than substituting a random
///      hash. A random hash would prove only that the game rejects garbage; a single wrong
///      field is what a real dishonest proposer would produce, and it is what the verifier
///      has to catch.
contract KVSFaultDisputeGameTest is Test {
    KauraxOneStepVerifier internal verifier;
    KauraxFaultDisputeGame internal game;

    address internal proposer = address(0xF00D);
    address internal challenger = address(0xBEEF);
    address internal bystander = address(0xCAFE);

    uint256 internal constant PROPOSER_BOND = 1 ether;
    uint256 internal constant CHALLENGER_BOND = 0.5 ether;
    uint64 internal constant TIMEOUT = 1 hours;
    uint64 internal constant MATURITY = 6 hours;

    /// @dev A single tuple rather than six top-level parameters: decoding six dynamic
    ///      values straight into storage exceeds the stack, and splitting the decode would
    ///      mean two places that have to agree about the fixture's layout.
    struct Scenario {
        bytes code;
        bytes32[] states;
        bytes[] stepProofs;
        bytes32 traceRoot;
        uint256 traceHeight;
        bytes finalState;
    }

    bytes internal code;
    bytes32[] internal states;
    bytes[] internal stepProofs;
    bytes32 internal traceRoot;
    uint256 internal traceHeight;
    KVSTypes.MachineState internal finalState;

    function setUp() public {
        verifier = new KauraxOneStepVerifier();
        game =
            new KauraxFaultDisputeGame(address(verifier), PROPOSER_BOND, CHALLENGER_BOND, TIMEOUT, MATURITY);

        Scenario memory sc = abi.decode(vm.parseBytes(vm.readFile("test/fixtures/kvs-game.hex")), (Scenario));
        code = sc.code;
        states = sc.states;
        stepProofs = sc.stepProofs;
        traceRoot = sc.traceRoot;
        traceHeight = sc.traceHeight;
        finalState = abi.decode(sc.finalState, (KVSTypes.MachineState));

        vm.deal(proposer, 100 ether);
        vm.deal(challenger, 100 ether);
        vm.deal(bystander, 100 ether);
    }

    // ------------------------------------------------------------ the fixture --

    function test_fixtureIsTheTraceItClaimsToBe() public view {
        assertEq(states.length, stepProofs.length + 1, "one more state than steps");
        assertEq(states.length, 9, "the scenario is eight instructions long");
        // The last state hash must be the hash of the struct shipped alongside it, or every
        // tampering test below would be tampering with something unrelated.
        assertEq(verifier.hashState(finalState), states[states.length - 1]);
        assertEq(uint256(finalState.status), uint256(KVSTypes.STOPPED));
    }

    /// @notice Replaying the honest trace through the verifier reproduces every state.
    /// @dev If this fails, nothing else in the file means anything.
    function test_verifierReproducesTheWholeHonestTrace() public view {
        for (uint256 i = 0; i < stepProofs.length; i++) {
            KauraxOneStepVerifier.StepProof memory p =
                abi.decode(stepProofs[i], (KauraxOneStepVerifier.StepProof));
            assertEq(verifier.step(states[i], p), states[i + 1], "trace diverges");
        }
    }

    // -------------------------------------------------------- honest execution --

    function test_honestProposerBeatsABaselessChallenge() public {
        uint256 gameId = _openGame(states[states.length - 1]);
        _descendToSteps(gameId);
        // The challenger agrees with every midpoint because every midpoint is true. That
        // walks the agreed boundary up to the last instruction.
        _bisectAgreeingWithEveryMidpoint(gameId);

        uint256 before = proposer.balance;
        _proveLeaf(gameId);

        assertEq(
            uint256(game.getGame(gameId).status),
            uint256(KauraxFaultDisputeGame.Status.RESOLVED_PROPOSER_WINS)
        );
        assertEq(
            game.withdrawable(proposer), PROPOSER_BOND + CHALLENGER_BOND, "winner is credited both bonds"
        );
        vm.prank(proposer);
        game.withdraw();
        assertEq(proposer.balance - before, PROPOSER_BOND + CHALLENGER_BOND, "winner takes both bonds");
    }

    // ------------------------------------------------- the proposer lied, four ways --

    function test_incorrectStateRootLoses() public {
        _assertProposerLosesWithFinalState(_tamper("wholly different"));
    }

    function test_incorrectStorageTransitionLoses() public {
        KVSTypes.MachineState memory s = finalState;
        s.storageRoot = keccak256("a storage root the program never produced");
        _assertProposerLosesWithFinalState(verifier.hashState(s));
    }

    function test_incorrectOpcodeResultLoses() public {
        // A wrong ADD shows up as a wrong stack root: the value on the stack differs.
        KVSTypes.MachineState memory s = finalState;
        s.stackRoot = keccak256("a stack holding the wrong sum");
        _assertProposerLosesWithFinalState(verifier.hashState(s));
    }

    function test_invalidGasAccountingLoses() public {
        KVSTypes.MachineState memory s = finalState;
        s.gas = s.gas + 1; // claiming one more unit of gas than the program actually left
        _assertProposerLosesWithFinalState(verifier.hashState(s));
    }

    function test_wrongProgramCounterLoses() public {
        KVSTypes.MachineState memory s = finalState;
        s.pc = s.pc + 1;
        _assertProposerLosesWithFinalState(verifier.hashState(s));
    }

    // ------------------------------------------------------------ malformed proofs --

    function test_stepProofWithTruncatedSiblingsIsRejected() public {
        uint256 gameId = _openGame(_tamper("lie"));
        _descendToSteps(gameId);
        // Step 1 is a PUSH, so it actually touches the stack. The final step of this
        // program is STOP, which consumes no proofs at all — tampering with a proof it
        // never reads proves nothing, and an earlier version of this test passed for
        // exactly that reason.
        _narrowToStep(gameId, 1);

        KauraxOneStepVerifier.StepProof memory p =
            abi.decode(stepProofs[1], (KauraxOneStepVerifier.StepProof));
        assertGt(p.stackSiblings.length, 0, "this step must touch the stack for the test to mean anything");

        // Cutting one sibling changes the tree height, so the fold lands on a root that
        // cannot match. A verifier accepting this would be proving something about a
        // different tree than the one committed.
        bytes32[] memory short = new bytes32[](p.stackSiblings[0].length - 1);
        for (uint256 i = 0; i < short.length; i++) {
            short[i] = p.stackSiblings[0][i];
        }
        p.stackSiblings[0] = short;

        vm.prank(bystander);
        vm.expectRevert();
        game.proveStep(gameId, p);
    }

    function test_stepProofWithATamperedLeafIsRejected() public {
        uint256 gameId = _openGame(_tamper("lie"));
        _descendToSteps(gameId);
        // Step 2 is ADD, which *reads* two stack slots. A PUSH would not do: its proof
        // asserts the destination slot is empty, and the verifier hardcodes that expected
        // zero rather than trusting the supplied leaf — so tampering with the leaf of a
        // push changes nothing, which is correct behaviour and a useless test.
        _narrowToStep(gameId, 2);

        KauraxOneStepVerifier.StepProof memory p =
            abi.decode(stepProofs[2], (KauraxOneStepVerifier.StepProof));
        assertGt(p.stackLeaves.length, 0, "this step must read from the stack");
        p.stackLeaves[0] = keccak256("a value that was never on the stack");

        vm.prank(bystander);
        vm.expectRevert();
        game.proveStep(gameId, p);
    }

    /// @notice The same protections hold when the verifier is called directly, without a
    ///         game in front of it. Nothing about the guarantee depends on the caller.
    function test_verifierItselfRejectsTamperedProofs() public {
        KauraxOneStepVerifier.StepProof memory p =
            abi.decode(stepProofs[2], (KauraxOneStepVerifier.StepProof));
        bytes32[] memory saved = p.stackSiblings[0];

        p.stackLeaves[0] = keccak256("fabricated operand");
        vm.expectRevert();
        verifier.step(states[2], p);

        p = abi.decode(stepProofs[2], (KauraxOneStepVerifier.StepProof));
        p.stackSiblings[0] = new bytes32[](saved.length);
        for (uint256 i = 0; i < saved.length; i++) {
            p.stackSiblings[0][i] = keccak256(abi.encode(saved[i]));
        }
        vm.expectRevert();
        verifier.step(states[2], p);
    }

    function test_stepProofForTheWrongStepIsRejected() public {
        uint256 gameId = _openGame(_tamper("lie"));
        _descendToSteps(gameId);
        _bisectAgreeingWithEveryMidpoint(gameId);

        // A proof whose pre-state is some earlier state does not answer the question the
        // game narrowed to, and the verifier says so rather than proving the wrong thing.
        KauraxOneStepVerifier.StepProof memory p =
            abi.decode(stepProofs[0], (KauraxOneStepVerifier.StepProof));
        vm.prank(bystander);
        vm.expectRevert();
        game.proveStep(gameId, p);
    }

    // ------------------------------------------------------------------ timeouts --

    function test_abandoningProposerLosesOnTimeout() public {
        uint256 gameId = _openGame(states[states.length - 1]);
        // The proposer never descends.
        vm.warp(block.timestamp + TIMEOUT + 1);

        uint256 before = challenger.balance;
        vm.prank(bystander); // permissionless on purpose
        game.resolveTimeout(gameId);

        assertEq(
            uint256(game.getGame(gameId).status), uint256(KauraxFaultDisputeGame.Status.RESOLVED_TIMEOUT)
        );
        vm.prank(challenger);
        game.withdraw();
        assertEq(challenger.balance - before, PROPOSER_BOND + CHALLENGER_BOND);
    }

    function test_abandoningChallengerLosesOnTimeout() public {
        uint256 gameId = _openGame(states[states.length - 1]);
        _descendToSteps(gameId);
        vm.prank(proposer);
        game.defend(gameId, states[4]);

        vm.warp(block.timestamp + TIMEOUT + 1);
        uint256 before = proposer.balance;
        game.resolveTimeout(gameId);
        vm.prank(proposer);
        game.withdraw();
        assertEq(proposer.balance - before, PROPOSER_BOND + CHALLENGER_BOND);
    }

    /// @notice Nobody ran the instruction, so the claim stands.
    /// @dev The challenger had every chance: submitting the proof is permissionless, so a
    ///      challenger who was actually right could have ended the game itself.
    function test_unprovenLeafResolvesToTheProposer() public {
        uint256 gameId = _openGame(_tamper("lie"));
        _descendToSteps(gameId);
        _bisectAgreeingWithEveryMidpoint(gameId);

        vm.warp(block.timestamp + TIMEOUT + 1);
        uint256 before = proposer.balance;
        game.resolveTimeout(gameId);
        vm.prank(proposer);
        game.withdraw();
        assertEq(proposer.balance - before, PROPOSER_BOND + CHALLENGER_BOND);
    }

    function test_timeoutBeforeTheDeadlineIsRejected() public {
        uint256 gameId = _openGame(states[states.length - 1]);
        vm.expectRevert();
        game.resolveTimeout(gameId);
    }

    // ------------------------------------------------------------------ griefing --

    function test_aClaimCannotBeChallengedTwice() public {
        uint256 claimId = _postClaim(states[states.length - 1]);
        vm.prank(challenger);
        game.challenge{value: CHALLENGER_BOND}(claimId);

        vm.prank(bystander);
        vm.expectRevert(KauraxFaultDisputeGame.AlreadyChallenged.selector);
        game.challenge{value: CHALLENGER_BOND}(claimId);
    }

    /// @dev Without this a proposer could challenge itself, burn a bond, and permanently
    ///      occupy the single game slot so no real challenger could ever open one.
    function test_aProposerCannotChallengeItsOwnClaim() public {
        uint256 claimId = _postClaim(states[states.length - 1]);
        vm.prank(proposer);
        vm.expectRevert(KauraxFaultDisputeGame.NotChallenger.selector);
        game.challenge{value: CHALLENGER_BOND}(claimId);
    }

    function test_wrongBondsAreRejectedOnBothSides() public {
        vm.prank(proposer);
        vm.expectRevert();
        game.postClaim{value: PROPOSER_BOND - 1}(states[0], states[8], 1);

        uint256 claimId = _postClaim(states[8]);
        vm.prank(challenger);
        vm.expectRevert();
        game.challenge{value: CHALLENGER_BOND + 1}(claimId);
    }

    function test_absurdLengthsAreRefused() public {
        vm.prank(proposer);
        vm.expectRevert();
        game.postClaim{value: PROPOSER_BOND}(states[0], states[8], 0);

        vm.prank(proposer);
        vm.expectRevert();
        game.postClaim{value: PROPOSER_BOND}(states[0], states[8], type(uint64).max);
    }

    function test_descentLengthIsBounded() public {
        uint256 gameId = _openGame(states[8]);
        vm.prank(proposer);
        vm.expectRevert();
        game.descend(gameId, type(uint64).max);
    }

    // ------------------------------------------------------------------- replays --

    function test_aResolvedGameCannotBeProvenAgain() public {
        uint256 gameId = _openGame(states[states.length - 1]);
        _descendToSteps(gameId);
        _bisectAgreeingWithEveryMidpoint(gameId);
        _proveLeaf(gameId);

        KauraxOneStepVerifier.StepProof memory p =
            abi.decode(stepProofs[stepProofs.length - 1], (KauraxOneStepVerifier.StepProof));
        vm.expectRevert(KauraxFaultDisputeGame.AlreadySettled.selector);
        game.proveStep(gameId, p);
    }

    function test_aResolvedGameCannotBeTimedOut() public {
        uint256 gameId = _openGame(states[states.length - 1]);
        _descendToSteps(gameId);
        _bisectAgreeingWithEveryMidpoint(gameId);
        _proveLeaf(gameId);

        vm.warp(block.timestamp + TIMEOUT + 1);
        vm.expectRevert(KauraxFaultDisputeGame.AlreadySettled.selector);
        game.resolveTimeout(gameId);
    }

    function test_bondsAreOnlyPaidOnce() public {
        uint256 gameId = _openGame(states[states.length - 1]);
        _descendToSteps(gameId);
        _bisectAgreeingWithEveryMidpoint(gameId);
        _proveLeaf(gameId);
        assertEq(game.withdrawable(proposer), PROPOSER_BOND + CHALLENGER_BOND);
        vm.prank(proposer);
        game.withdraw();
        assertEq(game.withdrawable(proposer), 0, "the credit is cleared before the transfer");
        assertEq(address(game).balance, 0, "the game holds nothing once the winner has pulled");

        vm.prank(proposer);
        vm.expectRevert(KauraxFaultDisputeGame.NothingToWithdraw.selector);
        game.withdraw();
    }

    // ---------------------------------------------------------------- turn order --

    function test_movesOutOfTurnAreRejected() public {
        uint256 gameId = _openGame(states[8]);

        vm.prank(challenger);
        vm.expectRevert();
        game.dispute(gameId, true); // not the challenger's turn yet

        vm.prank(challenger);
        vm.expectRevert(KauraxFaultDisputeGame.NotProposer.selector);
        game.descend(gameId, 1); // only the proposer descends
    }

    function test_descentIsRefusedWhileStillBisecting() public {
        uint256 gameId = _openGame(states[8]);
        _descendToSteps(gameId);
        vm.prank(proposer);
        vm.expectRevert(KauraxFaultDisputeGame.StillBisecting.selector);
        game.descend(gameId, 2);
    }

    function test_descentIsRefusedBelowTheStepLevel() public {
        uint256 gameId = _openGame(states[8]);
        _descendToSteps(gameId); // now at STEP level with eight units
        _bisectAgreeingWithEveryMidpoint(gameId); // narrowed to one instruction
        vm.prank(proposer);
        vm.expectRevert();
        game.descend(gameId, 1);
    }

    function test_unknownGamesAndClaimsRevert() public {
        vm.expectRevert(KauraxFaultDisputeGame.UnknownGame.selector);
        game.getGame(999);
        vm.expectRevert(KauraxFaultDisputeGame.UnknownClaim.selector);
        game.getClaim(999);
    }

    // ------------------------------------------------------------- claim lifecycle --

    function test_anUnchallengedClaimReleasesItsBondAfterMaturity() public {
        uint256 claimId = _postClaim(states[8]);
        vm.warp(block.timestamp + MATURITY + 1);

        uint256 before = proposer.balance;
        vm.prank(proposer);
        game.withdrawClaimBond(claimId);
        assertEq(proposer.balance - before, PROPOSER_BOND);
    }

    function test_anImmatureClaimKeepsItsBond() public {
        uint256 claimId = _postClaim(states[8]);
        vm.prank(proposer);
        vm.expectRevert();
        game.withdrawClaimBond(claimId);
    }

    function test_aChallengedClaimCannotBeWithdrawn() public {
        uint256 claimId = _postClaim(states[8]);
        vm.prank(challenger);
        game.challenge{value: CHALLENGER_BOND}(claimId);

        vm.warp(block.timestamp + MATURITY + 1);
        vm.prank(proposer);
        vm.expectRevert(KauraxFaultDisputeGame.AlreadyChallenged.selector);
        game.withdrawClaimBond(claimId);
    }

    // --------------------------------------------------------------------- fuzz --

    /// @notice Whatever the challenger answers, the game reaches a single instruction and
    ///         the invariant "agreed at lo, disputed at hi" holds at every step.
    /// @dev The bisection is where a subtle off-by-one would hide, and it would hide well:
    ///      a game that converged to the wrong pair would still resolve, just against the
    ///      wrong party.
    function testFuzz_bisectionAlwaysConvergesToOneInstruction(uint256 _answers) public {
        uint256 gameId = _openGame(states[8]);
        _descendToSteps(gameId);

        for (uint256 round = 0; round < 8; round++) {
            KauraxFaultDisputeGame.Game memory g = game.getGame(gameId);
            if (g.status == KauraxFaultDisputeGame.Status.AWAITING_PROOF) break;

            assertLt(g.lo, g.hi, "the range never inverts");
            uint64 mid = g.lo + (g.hi - g.lo) / 2;

            vm.prank(proposer);
            game.defend(gameId, states[mid]);

            vm.prank(challenger);
            game.dispute(gameId, (_answers >> round) & 1 == 1);
        }

        KauraxFaultDisputeGame.Game memory end = game.getGame(gameId);
        assertEq(
            uint256(end.status),
            uint256(KauraxFaultDisputeGame.Status.AWAITING_PROOF),
            "every path ends at a single instruction"
        );
        assertEq(end.hi, end.lo + 1);
        assertEq(end.loClaim, states[end.lo], "the agreed boundary is a real state");
    }

    /// @notice An honest proposer wins from any bisection path a challenger can choose.
    /// @dev The stronger of the two fuzz properties: it is not enough that the game
    ///      terminates, it has to terminate against the party that was actually wrong.
    function testFuzz_honestProposerWinsWhateverTheChallengerAnswers(uint256 _answers) public {
        uint256 gameId = _openGame(states[8]);
        _descendToSteps(gameId);

        for (uint256 round = 0; round < 8; round++) {
            KauraxFaultDisputeGame.Game memory g = game.getGame(gameId);
            if (g.status == KauraxFaultDisputeGame.Status.AWAITING_PROOF) break;
            uint64 mid = g.lo + (g.hi - g.lo) / 2;
            vm.prank(proposer);
            game.defend(gameId, states[mid]);
            vm.prank(challenger);
            game.dispute(gameId, (_answers >> round) & 1 == 1);
        }

        KauraxFaultDisputeGame.Game memory end = game.getGame(gameId);
        KauraxOneStepVerifier.StepProof memory p =
            abi.decode(stepProofs[end.lo], (KauraxOneStepVerifier.StepProof));
        vm.prank(bystander);
        game.proveStep(gameId, p);

        assertEq(
            uint256(game.getGame(gameId).status),
            uint256(KauraxFaultDisputeGame.Status.RESOLVED_PROPOSER_WINS)
        );
    }

    /// @notice A winner that cannot receive ETH must not be able to freeze the game.
    ///
    /// @dev The regression this locks in: settlement used to pay the winner inside
    ///      `proveStep`. A challenger contract with no payable fallback therefore made every
    ///      call to `proveStep` revert — and since a game at the leaf can be resolved no
    ///      other way, both bonds were locked permanently. It cost the griefer its own bond
    ///      and cost the proposer the same, which is a trade a griefer will happily take.
    function test_aWinnerThatRejectsEtherCannotFreezeTheGame() public {
        RejectsEther hostile = new RejectsEther();
        vm.deal(address(hostile), 10 ether);

        uint256 claimId = _postClaim(_tamper("lie"));
        vm.prank(address(hostile));
        uint256 gameId = game.challenge{value: CHALLENGER_BOND}(claimId);

        vm.prank(proposer);
        game.descend(gameId, 1);
        vm.prank(proposer);
        game.descend(gameId, uint64(stepProofs.length));
        for (uint256 i = 0; i < 16; i++) {
            KauraxFaultDisputeGame.Game memory g = game.getGame(gameId);
            if (g.status != KauraxFaultDisputeGame.Status.PROPOSER_TURN) break;
            uint64 mid = g.lo + (g.hi - g.lo) / 2;
            vm.prank(proposer);
            game.defend(gameId, states[mid]);
            vm.prank(address(hostile));
            game.dispute(gameId, true);
        }

        // Resolution succeeds even though the winner cannot be paid.
        _proveLeaf(gameId);
        assertEq(
            uint256(game.getGame(gameId).status),
            uint256(KauraxFaultDisputeGame.Status.RESOLVED_CHALLENGER_WINS)
        );
        assertEq(game.withdrawable(address(hostile)), PROPOSER_BOND + CHALLENGER_BOND);

        // Only the pull fails, and only for the party that made it fail.
        vm.prank(address(hostile));
        vm.expectRevert(KauraxFaultDisputeGame.TransferFailed.selector);
        game.withdraw();
    }

    // ---------------------------------------------------------------------- gas --

    /// @notice Measures what one-step verification actually costs, per opcode class.
    /// @dev The proposal claimed a budget of 5,000,000 gas for verification. A claim like
    ///      that is worth nothing unmeasured, so this prints the real figures and fails if
    ///      any step exceeds the budget.
    function test_stepVerificationStaysInsideTheGasBudget() public {
        uint256 worst;
        for (uint256 i = 0; i < stepProofs.length; i++) {
            KauraxOneStepVerifier.StepProof memory p =
                abi.decode(stepProofs[i], (KauraxOneStepVerifier.StepProof));
            uint256 before = gasleft();
            verifier.step(states[i], p);
            uint256 used = before - gasleft();
            emit log_named_uint(string.concat("step ", vm.toString(i), " gas"), used);
            if (used > worst) worst = used;
        }
        emit log_named_uint("worst step (this scenario includes SSTORE and SLOAD)", worst);
        assertLt(worst, 5_000_000, "one-step verification must fit the stated budget");
    }

    // ------------------------------------------------------------------ helpers --

    function _tamper(string memory _what) internal pure returns (bytes32) {
        return keccak256(bytes(_what));
    }

    function _postClaim(bytes32 _end) internal returns (uint256 claimId) {
        vm.prank(proposer);
        claimId = game.postClaim{value: PROPOSER_BOND}(states[0], _end, 1);
    }

    function _openGame(bytes32 _end) internal returns (uint256 gameId) {
        uint256 claimId = _postClaim(_end);
        vm.prank(challenger);
        gameId = game.challenge{value: CHALLENGER_BOND}(claimId);
    }

    /// @dev One block holding one transaction holding eight instructions.
    function _descendToSteps(uint256 _gameId) internal {
        vm.prank(proposer);
        game.descend(_gameId, 1); // BLOCK -> TRANSACTION
        vm.prank(proposer);
        game.descend(_gameId, uint64(stepProofs.length)); // TRANSACTION -> STEP
    }

    function _bisectAgreeingWithEveryMidpoint(uint256 _gameId) internal {
        for (uint256 i = 0; i < 16; i++) {
            KauraxFaultDisputeGame.Game memory g = game.getGame(_gameId);
            if (g.status != KauraxFaultDisputeGame.Status.PROPOSER_TURN) break;
            uint64 mid = g.lo + (g.hi - g.lo) / 2;
            vm.prank(proposer);
            game.defend(_gameId, states[mid]);
            vm.prank(challenger);
            game.dispute(_gameId, true);
        }
    }

    /// @dev Drives the bisection so the game ends on a chosen instruction. Agreeing when the
    ///      target is at or above the midpoint and disagreeing otherwise is just binary
    ///      search, and it lets a test aim at a step with the properties it needs.
    function _narrowToStep(uint256 _gameId, uint64 _target) internal {
        for (uint256 i = 0; i < 32; i++) {
            KauraxFaultDisputeGame.Game memory g = game.getGame(_gameId);
            if (g.status != KauraxFaultDisputeGame.Status.PROPOSER_TURN) break;
            uint64 mid = g.lo + (g.hi - g.lo) / 2;
            vm.prank(proposer);
            game.defend(_gameId, states[mid]);
            vm.prank(challenger);
            game.dispute(_gameId, _target >= mid);
        }
        KauraxFaultDisputeGame.Game memory end = game.getGame(_gameId);
        assertEq(end.lo, _target, "narrowing did not land on the intended instruction");
    }

    function _proveLeaf(uint256 _gameId) internal {
        KauraxFaultDisputeGame.Game memory g = game.getGame(_gameId);
        KauraxOneStepVerifier.StepProof memory p =
            abi.decode(stepProofs[g.lo], (KauraxOneStepVerifier.StepProof));
        vm.prank(bystander);
        game.proveStep(_gameId, p);
    }

    function _assertProposerLosesWithFinalState(bytes32 _wrongEnd) internal {
        uint256 gameId = _openGame(_wrongEnd);
        _descendToSteps(gameId);
        _bisectAgreeingWithEveryMidpoint(gameId);

        uint256 before = challenger.balance;
        _proveLeaf(gameId);

        assertEq(
            uint256(game.getGame(gameId).status),
            uint256(KauraxFaultDisputeGame.Status.RESOLVED_CHALLENGER_WINS),
            "the verifier should have contradicted the proposer"
        );
        vm.prank(challenger);
        game.withdraw();
        assertEq(challenger.balance - before, PROPOSER_BOND + CHALLENGER_BOND);
    }
}

/// @dev Refuses every incoming transfer, which is the whole point.
contract RejectsEther {
    receive() external payable {
        revert("no");
    }
}
